name: Keep Render Bot Alive
on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to Render bot
        run: curl -s https://snipnbot.onrender.com/
